baseURL = 'http://localhost:1313/'
locale = 'it-it'
defaultContentLanguage = 'it'
title = 'Le stelle più affascinanti del cielo'

theme = 'hugo-book'

[params]
  BookSection = '*'
  math = true

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true

        [markup.goldmark.extensions.passthrough.delimiters]
          block = [
            ["$$", "$$"]
          ]
          inline = [
            ["$", "$"]
          ]

        [markup.goldmark.renderer]
          unsafe = true